name: Address Sanitizer analysis

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'ID associated to the workflow'
        required: true
        type: string
      colcon_meta:
        description: 'Optional Path of the colcon meta file'
        required: false
        type: string
      cmake_args:
        description: 'Optional CMake Compilation Flags'
        required: false
        type: string
      ctest_args:
        description: 'Optional CTest Testing Flags'
        required: false
        type: string
      discovery_server_branch:
        description: 'Branch or tag of Discovery Server repository (https://github.com/eProsima/Discovery-Server)'
        required: true
        default: 'master'
      fastdds_branch:
        description: 'Branch or tag of Fast DDS repository (https://github.com/eProsima/Fast-DDS)'
        required: true
        default: 'master'

  pull_request:
    types:
      - review_requested
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  address-sanitizer:
    uses: ./.github/workflows/reusable-sanitizer.yml
    if: ${{ (
              !contains(github.event.pull_request.labels.*.name, 'skip-ci') &&
              !contains(github.event.pull_request.labels.*.name, 'no-test') &&
              !contains(github.event.pull_request.labels.*.name, 'conflicts')
            ) }}
    with:
      label: ${{ inputs.label || 'address-sanitizer' }}
      colcon_meta: ${{ inputs.colcon_meta || 'src/fastrtps/.github/workflows/config/asan_colcon.meta' }}
      cmake_args: ${{ inputs.cmake_args || '' }}
      ctest_args: ${{ inputs.ctest_args || '--label-exclude xfail --timeout 300' }}
      fastdds_branch: ${{ github.head_ref || inputs.fastdds_branch || 'master' }}
      asan_report: 'true'

  discovery-server-address-sanitizer:
    uses: ./.github/workflows/reusable-sanitizer.yml
    if: ${{ (
              !contains(github.event.pull_request.labels.*.name, 'skip-ci') &&
              !contains(github.event.pull_request.labels.*.name, 'no-test') &&
              !contains(github.event.pull_request.labels.*.name, 'conflicts')
            ) }}
    with:
      label: ${{ inputs.label || 'discovery-server-address-sanitizer' }}
      colcon_meta: ${{ inputs.colcon_meta || 'src/fastrtps/.github/workflows/config/asan_colcon.meta' }}
      cmake_args: ${{ inputs.cmake_args || '' }}
      ctest_args: ${{ inputs.ctest_args || '--label-exclude xfail --timeout 300' }}
      fastdds_branch: ${{ github.head_ref || inputs.fastdds_branch || 'master' }}
      discovery_server_branch: ${{ inputs.discovery_server_branch || 'master' }}
      asan_discovery_server_report: 'true'
